name: Release
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 0" # At 00:00 on Sunday (weekly)

env:
  BASE: /
  USER: study-deploy
  SERVER: studyathome.technikum-wien.at
  DEST: /var/www/html/hub-public
  SSH_OPTS: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeGit Build Dependencies
        run: sudo apt install libkrb5-dev
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: hub
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      PASS: ${{ secrets.DEPLOY_USER_KEY }}
    steps:
      - name: Download Build Result
        uses: actions/download-artifact@v3
        with:
          name: hub
      - name: Test Check
        run: sshpass -p ${PASS} ssh ${SSH_OPTS} ${USER}@${SERVER} "echo ${DEST}"
      - name: Test Check 2
        env:
          CMD: "echo ${DEST}"
        run: sshpass -p ${PASS} ssh ${SSH_OPTS} ${USER}@${SERVER} ${CMD}
      - name: Check Prerelease 2
        run: sshpass -p ${PASS} ssh ${SSH_OPTS} ${USER}@${SERVER} "ls ${DEST}/next"
      - name: Check Prerelease
        id: prerelease
        env:
          CMD: [ -d ${DEST}/next ]
        run: echo "exists=$(sshpass -p ${PASS} ssh ${SSH_OPTS} ${USER}@${SERVER} ${CMD})" >> $GITHUB_OUTPUT
      - name: Test Check
        if: ${{ steps.prerelease.exists }}
        run: echo "Prerelease exists"
      - name: Test Check 2
        if: ${{ !steps.prerelease.exists }}
        run: echo "Prerelease doesn't exist"
      - name: Download Prerelease
        run: echo sshpass -p ${PASS} scp ${SSH_OPTS} -r ${USER}@${SERVER}:${DEST}/next next
      - name: Delete Content from Server
        run: sshpass -p ${PASS} ssh ${SSH_OPTS} ${USER}@${SERVER} "echo rm -rf ${DEST}/*"
      - name: Delete Content from Server
        run: sshpass -p ${PASS} ssh ${SSH_OPTS} ${USER}@${SERVER} "echo rm -rf ${DEST}/*"
      - name: Upload Build to StudyATHome Server
        run: echo sshpass -p ${PASS} scp ${SSH_OPTS} -r * ${USER}@${SERVER}:${DEST}/
  # We don't know when the site will be deployed, we just wait a few seconds
  # Better solutions can be found
  delay:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Delay for 120 seconds
        run: sleep 120s
  algolia:
    needs: [deploy, delay]
    uses: ./.github/workflows/algolia.yml
    with:
      delete_index: true
    secrets: inherit
